# Generated by Django 5.1.2 on 2024-11-05 08:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Juguete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_juguete', models.CharField(max_length=100)),
                ('edad_juego', models.IntegerField()),
                ('cantidad_juguete', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(choices=[('C', 'CAIXA'), ('B', 'BBVA'), ('U', 'UNICAJA'), ('I', 'ING')], max_length=1)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banco_cliente', to='examen.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='juguete',
            field=models.ManyToManyField(related_name='juguete_cliente', to='examen.juguete'),
        ),
        migrations.CreateModel(
            name='Juguetería',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(max_length=100)),
                ('juguetes_vendidos', models.IntegerField()),
                ('juguetes_devueltos', models.IntegerField()),
                ('juguete', models.ManyToManyField(related_name='juguete_tienda', to='examen.juguete')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='juguetería',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugueteria_cliente', to='examen.juguetería'),
        ),
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.CharField(max_length=100)),
                ('fecha_voto', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_voto', to='examen.cliente')),
                ('juguete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voto_jugete', to='examen.juguete')),
            ],
        ),
    ]
